### ISSUE TITLE
qarchive question

### ISSUE THREAD

**Issue by ghost** [antony-jr/ama#16]
So, today I stumbled upon your lib QArchive and decided to try it for myself. But I can't get it work. Can you confirm if it works for you? 
I'm running latest Mint distro, latest Qt (5.10.1) and I have libarchive installed. I am trying to run code from  your examples but it doesn't work. Am I doing something wrong?

**Comment by ghost** [comment]
Nevermind, I got it. But still, example code doesn't seem to work. So yeah, you might want to recheck that one.

**Comment by antony-jr** [comment]
Thank you for the point out , Will check that out.

**Comment by antony-jr** [comment]
@Senarce By **not working** , do you mean that it does not compile ? I guess I did not mention it in the readme , Older versions of **libarchive** ( < 3.3.2 ) will **not have password support** since libarchive is doing encryption as a experimental thing. So if you have a older version of libarchive which does not support passwords then the example compile will fail , I think I can fix this by a ```#if```.

**Can you try compiling only the examples which does not use the password feature ?**

**Comment by ghost** [comment]
Yeah, my bad, I should've explained it in detail. I was following guide on GH pages and when I tried this one: https://antony-jr.github.io/QArchive/docs/UsingExtractor.html it didn't work. It did compile but did nothing. I imagine something wrong with `setFunc()`. But then I decided to try `connect()` from `QObject `and it worked like a charm.

**Comment by antony-jr** [comment]
@Senarce Thanks , I just checked it and it really did not work , It will be fixed soon.

**Comment by antony-jr** [comment]
> I imagine something wrong with setFunc(). But then I decided to try connect() from QObjectand it worked like a charm.

The thing is that ```setFunc``` works but does not work only on that specific code.

**Comment by antony-jr** [comment]
The code works if I declare it explicitly , like this -> ``` QArchive::Extractor Extractor("test.7z"); ``` and then do the extraction. So I suppose this is a limitation with **signal and slots** ? Soon will update the examples in the documentation.

**Comment by antony-jr** [comment]
@Senarce Updated the documentation , Make sure to clear your cache else you will see the old documentation ( This is done by your browser for optimization ). **Thank You for reporting the issue**.
