### ISSUE TITLE
Hey! 😥

### ISSUE THREAD

**Issue by sunshiner0ses** [antony-jr/ama#17]
I respect your work a lot and I've seen many good things about your creation of Instagram-py and honestly i know u dropped the case but i really do need your help..

it would mean the world if u could help me get an account, it isn't really for ill will but yea i hope you'll get back to me, thank u.

**Comment by antony-jr** [comment]
@sunshiner0ses  Well science is a **double edged sword** , So whats up ?

**Comment by jordanhoxl** [comment]
Hey Anthony, the whole coding thing to me it’s just another language that I could never get it. Possible to help me recover an Instagram account password? 
Thank you.

**Comment by antony-jr** [comment]
@jordanhoxl you know that you are just trying hundreds of passwords until your account logs in successfully? , This type of attack is the safest and the most slowest one. You can only recover your account if the password is present in the wordlist. Are you sure you want to try this ? Because most of the time it fails if the wordlist is weak. ( You can create a wordlist from your last remembered password ).

Live boot to kali linux and then try this -> https://www.youtube.com/watch?v=nNfSyI_Q9SM

**Comment by antony-jr** [comment]
I'm thinking about rising support for instagram-py with recovery option. But it might take some time so until then you have to use the old code.

**Comment by jordanhoxl** [comment]
Hi Antony,

Thanks for the prompt reply. If that’s the case. Would you be able to hack
the ig account for me? I’m willing to pay for your help on that.

Thank you!

**Comment by antony-jr** [comment]
@jordanhoxl Thanks for the offer but thats **illegal** and I'm no good at this stuff. But I'm thinking about making this easier and less prone to crashes.
