### ISSUE TITLE
IG Instagram-Py

### ISSUE THREAD

**Issue by Demaiomr** [antony-jr/ama#18]
Antony, 

I have questions about the Instagram-Py. Is an email I address I can contact you through?

**Comment by antony-jr** [comment]
@Demaiomr You can contact me through , antonyjr@protonmail.com

**Comment by vimalhack007** [comment]
sir why we need victim verification if we doing Bruteforce attack. Bruteforce attack guess itself the right password right? i wanted to hack an inactive Instagram account.  Sorry for my bad English       


-thanks sir

**Comment by antony-jr** [comment]
@vimalhack007 The challenge in brute force attack on a web service is how we check if a password is authentic or not. And so we do this by directly connecting with the web service(in this case Instagram). So the whole password authentication is done on the server side , we just need to observe the cues in the server response in order to check if a password is right or wrong. So if Instagram detects abnormal amount of password submission for a particular account , it gets alerted and thus the user verification when he or she logs in successfully.

**Comment by vimalhack007** [comment]
Co can't we do with inactive Instagram account? Is there any other way to
do that ?😅

**Comment by antony-jr** [comment]
@vimalhack007 None , to the best of my knowledge. Inactive Instagram accounts are pretty much lost. Unless you can contact Instagram to claim it legally.

**Comment by vimalhack007** [comment]
Thanks for the information dude
