### ISSUE TITLE
Instagram-py

### ISSUE THREAD

**Issue by Laurenxx** [antony-jr/ama#23]
Hi, 

What should I do if the account I’m trying to hack is inactive? Somebody took my account and I don’t think they’re using it, how should I get it back in this case?

**Comment by antony-jr** [comment]
@Laurenxx Configure your **Tor Server** to use only the **exit nodes** which are located at the region where the account used to login in the past. Now use **Instagram-Py**(Depricated and Deleted , Sorry) to brute force your account and when it finds the password , You can login to your account.(This time your account will not blocked since instagram thinks that the tries are from your phone.)

**IMPORTANT** : This method only works if you do the brute force attack for the first time , i.e If you have conducted a brute force attack without the above mentioned method , The account will be blocked forever until the original user logs back in and verifies.
