### ISSUE TITLE
Please help me broo

### ISSUE THREAD

**Issue by muron16** [antony-jr/ama#27]
I need to know the best Operating system for hack 2018 because i try in Kali Linux it failed bro

**Comment by antony-jr** [comment]
Whats the challenges you faced when you tried installing Kali Linux ? Give me some details.

See [this](https://fossbytes.com/10-best-operating-systems-for-ethical-hacking-and-penetration-testing-2016/) blog post for more information on some alternatives to Kali Linux but please see that all other operating systems are very similar to Kali Linux and vice versa.(Because they all use the same kernel)
