### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by ProxySniper** [antony-jr/ama#28]
Hey I was wondering with your code, what are you actually able to do by hacking other peoples Instagram accounts? Like can I steal their username, post pics, etc?

**Comment by antony-jr** [comment]
@ProxySniper Hmm... I just did it for fun , To be honest I did to test my own skills to implement a good hacking tool. You see there is a huge uprise of self-proclaimed hackers (I don't consider myself a hacker) who write code which don't really do the job it promised , Thus I thought I should do some real tool that people can use and not get fooled. To make it worse , These self-proclaimed hackers gets a huge fan base , Because their fans don't really know what he/she is doing is real or fake(Most of the code looks like its written by a 10 year old).

> what are you actually able to do by hacking other peoples Instagram accounts? Like can I steal their username, post pics, etc?

*Yes , you can do everything. But I did it to see the real side of people and also take down some cyberbullies.*
