### ISSUE TITLE
ig account hack

### ISSUE THREAD

**Issue by bonalas** [antony-jr/ama#34]
hey sir.. i would lke to ask you for help.. i have been monitoring an account with the username that i wanted for almost 3 years now. it is an inactive account with 0 followers, 0 followings and 0 posts. I really want that account so badly as the name is sentimental for myself. Hope you notices my message.. i have ran out of options..

**Comment by sohamn21** [comment]
hey if you have kali linux here is the help
https://github.com/thelinuxchoice/instainsane

instainsane is an Shell Script to perform multi-threaded brute force attack against Instagram, this script can bypass login limiting and it can test infinite number of passwords with a rate of about 1000 passwords/min with 100 attemps at once.

Legal disclaimer:

Usage of InstaInsane for attacking targets without prior mutual consent is illegal. It's the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

Features

    Multi-thread (100 attempts at once)
    Save/Resume sessions
    Anonymous attack through TOR
    Check valid usernames
    Default password list (best +39k 8 letters)
    Check and Install all dependencies

**Comment by mcgregor7** [comment]
same thing for me...please hit me up you can help me too,
