### ISSUE TITLE
Can I use several wordlist files at once?

### ISSUE THREAD

**Issue by layzvoxone** [antony-jr/ama#44]
Hey! I started using Instagram-py and it works great, but it's a pain in the ass to change the wordlist every time one is over.
Is there a way to use several wordlist files at once?

**Comment by antony-jr** [comment]
@layzvoxone simply use multiple instance(That's the only solution). Is this tool still working? **I dropped support for it a long time ago.**

**Comment by layzvoxone** [comment]
Okay thank you! Yeah it still works, although did you make another tool to crack instagram passwords?
Oh and I have a question, is there a way to make the delay shorter between the tries? It's currently a 3 seconds delay for me

**Comment by antony-jr** [comment]
>  although did you make another tool to crack instagram passwords?

No, But I do have a plan to hack any Instagram account instantly(or simply spy on their DM) when they are connected to your network. So you simply have to convince your victim to use your WIFI connection or use the evil twin method to hijack their WIFI connection. But I think it would take a lot of time and I don't have time for it. *But its way better than brute force*. I might implement it sometime later.

> Oh and I have a question, is there a way to make the delay shorter between the tries? It's currently a 3 seconds delay for me

I think the delay is important, since the attack is over the internet we don't want to be suspicious on sending request every nano seconds which would simply cut our connection off thinking that we are making a DDOS attack(see HTTP 403). **But I think a true multi-threading solution is needed to use all cores to make the attack way faster and accurate but this makes it very complex to design the tool**. So simply using the same design principles for a multi-threaded environment may render the accuracy to 80 percent or even lower.

**Comment by layzvoxone** [comment]
Nice that would be super cool!
