### ISSUE TITLE
old project support 

### ISSUE THREAD

**Issue by Knrd2** [antony-jr/ama#46]
Hey, ive read about your instagram-py project. Is it still working or do you have any other suggestions about good programs like yours? Ive tried out a lot already to find one password but wasn't successful, like a quote of yours is saying "Why would people even use these tools which does not even follow a good code base!"

Appreciate your answer!

**Comment by antony-jr** [comment]
@Knrd2 Some folks say that the tool is still working but I dropped the project because I didn't want to abuse the Tor project. Also if large enough users use the tool at the same time, There is a high chance that all IPs in the Tor network might get blocked. It is also worth to note that this is officially fixed by **Facebook**(See https://github.com/umeshshinde19/InstagramBrute and https://github.com/eyalmazuz/ThreatIntelligenceCorpus/blob/c47f9d2b7ba92e0cbba71c67b938a49e055c5cdc/Corpus/securityaffairs_instagram.html.txt).

All these implementation look very similar, I can't tell who copied from who. Only some respect attribution.

For now, using brute force is really a bad idea. I have a another technique in mind but due to the **quarantine** I can't buy the stuff I needed to do the experiment. But I might find another way to do it without using external hardware.

I was planning for the project for a long time but couldn't find time because of college, Now I have all the time I want.
