### ISSUE TITLE
What engaged to start using linux? And how did you learn?

### ISSUE THREAD

**Issue by lucidtyper** [antony-jr/ama#49]
I'm just curious how did you start with your adventure in the Linux world :smile:

**Comment by antony-jr** [comment]
I started out with Windows (*Windows XP*) like most people. When I was young all I wanted was to play games that the cool kids were playing. **Ignorance is a bliss, it was wonderful because everything seemed so simple back then (I guess tech back then was simple as well [2000s I guess]).**

Like the majority of the population **linux** was never in my vocabulary. I did not even knew there was OSes other than Windows and OSX. (*TL;DR I got really comfortable with installing operating systems, messing around with BIOS and getting around in Windows.*)

Like many I was really curious about Hacking (*Hacking is even now a very popular trend*, nowadays it's mainly know because of bug bounty but back then it was for the thrills). I really wanted to know more about **REAL HACKING**(in 2009-ish, it was really hard to get resources on that subject). *Google always returns fake hacking videos, that too in windows*.

**The first time I came to know about GNU/Linux was because of Offensive Security (The folks behind Backtrack Linux and Kali Linux)**. To learn about real hacking I used Backtrack linux in **Virtual box** first and then used it in live cd.

I used *Offensive Security's* syllabus to learn a lot of hacking and pentesting techniques. (*TL;DR I've done a lot of pentesting in the past*) (I remember struggling with a lot of topics since I had no CS background, even ignored a lot) (Here I learned a lot of linux commands too, very complicated ones like iptables which I never understood at the time)

At this moment **I learnt that computer science is much more interesting and amazing than hacking which is a very small part of CS**.

**Now my journey started on learning programming languages and everything related to computer science. Like number system, data structures, cryptography, basic web development and etc..** (I still remember reading college level CS subjects when I was in middle school)

*My first programming language was **Visual Basic**, **C#** and finally **C***. (Remember I was still dual booting Kali Linux and Windows at this stage. BTW I was self-thought).

> **Side Note**: My Anime Journey also started around this time xD :laughing:

**Dennis M. Ritchie was my very first inspiration. I learnt C programming from his book. I came to know about Unix and it's relationship to GNU/Linux from the preface of the book. I followed this book religiously and I did every exercise.**

**This is when I started to dual boot Ubuntu Linux (it was the time of Ubuntu 10.x I think). I was religiously following and learning from Dennis Ritchie's book. I learnt about basic linux commands from this book itself(I learnt lot of them from internet with offensive security syllabus earlier too but this made me understand the commands more clearly), I also learnt about linux file system structure from this book and linker/loader stuff. Basic structure of a C project, like makefiles and such.** *If you followed the book you would know we would be spending most of our time re-writing unix commands which was also linux commands* (few notable ones like grep)

> I really liked "The Unix philosophy". I also learnt about open source and popular folks in the industry.

After completing the book, I started to learn about a lot of programming languages and did a lot of personal projects that were lost (This was around 2013 to present. **TL;DR I deleted a previous github account which had all this source code**) 

At the same time I started **distro hopping** from **Ubuntu to Fedora to to Linux Mint to Arch Linux (Used this the longest, 4 years I think)  to Manjaro Linux (mainly because it was getting tedious installing Arch linux, it was no longer a challenge)** then now **OpenSUSE Tumbleweed**.

---


@MrLinuxOsu I've made this short as possible. :+1: for asking this question!

Regards,
Antony Jr. :heart:
