### ISSUE TITLE
i want to just say thanks for your tool insta insane:) 

### ISSUE THREAD

**Issue by princeofhacking** [antony-jr/ama#51]

**Comment by antony-jr** [comment]
@princeofhacking Insta insane is not made by me. It copies my algorithm but it's a bash rewrite. Also I don't think the tool is **NOT** capable of cracking any instagram account because **brute force attacks have very low success rate** and **insta insane gets false positives because it uses multi threading without any concern. It simply copied my algo, it needs to modify it to support multi threading.**

So if you had any success with that tool you should be thanking that author because I dropped support for these hacking tools way long ago because **it abuses the TOR Project** and **it has low rate of success**.
