### ISSUE TITLE
Seeking Feedback and Guidance for My Open Source Project

### ISSUE THREAD

**Issue by fxdeniz** [antony-jr/ama#55]
Hi @antony-jr,

I hope this message finds you well.
I've been following your work on GitHub for some time now, and I'm truly impressed by your contributions to the open-source community.
I'm the creator of an open-source project called NeSync ([GitHub link](https://github.com/fxdeniz/NeSync)), which is licensed under GPLv3.
NeSync is aimed at offline file synchronization & backup with user privacy in mind.

I admire your experience in the open-source world and would greatly appreciate your feedback and guidance on NeSync.
Specifically, I'm interested in:

1. Your thoughts on NeSync and any suggestions for improvement.
2. Strategies to increase its visibility and reach a wider audience.
3. Whether you would consider starring the project if you find it valuable.
4. Any insights on how to effectively promote and grow an open-source project.

Your expertise would be invaluable to me, and I understand that your time is precious.
I'm grateful for any insights or advice you can provide.

Thank you for considering my request. I look forward to hearing from you.

Best regards,
@fxdeniz (Deniz Yilmazok)

**Comment by antony-jr** [comment]
Greetings Deniz (@fxdeniz),

I don't know if I'm that good of open source developer but here are my 2 cents,

> Your thoughts on NeSync and any suggestions for improvement.

NeSync is a cool idea but needs a lot of work. If done right this could be very useful for artist and researchers. I would like to have program like this to watch my important thesis for my masters which I change quite often with full history, this can be done with Microsoft OneDrive in Windows but it's not local and not open source, and Google Docs already have this but no backup if no internet which is deal-breaker for me in the existing systems. 

Another solution is git which I use currently but it can be tedious to do git commit on every update. 

So the NeSync has some use-cases but it needs a lot of work, the following are something I think needs to improve,

* The user interface, serious improvement needed but ok for alpha. 
* *Get away from Qt as much as possible*, I know this is confusing since I do a lot of software using Qt but I regret this since it made me dumber, nowadays I'm exploring new ways to implement my ideas. I would suggest you write your core back-end in pure C++ or Rust to make it independent of Qt, it will make you think critically. Also a lot of efficient libraries other than Qt exists for this specific task which can do this much more efficient. **Bottom line, don't be a Frameworker** (See https://www.youtube.com/watch?v=UowtlZB2a70). But Qt does make it more easy to make your app cross-platform.

* Ability to connect with Google Drive or OneDrive or Nextcloud (This should be future enhancements)
* Make this cross-platform, especially for Android or iOS.
* Use CI/CD for deploying releases, don't build locally and upload.

> Strategies to increase its visibility and reach a wider audience.

This is quite difficult topic for me but I think I know the recipe for this but never achieved it myself, this is basic stuff
you will hear from any open-source developer. 

* Use link aggregator like **Reddit**, this could back fire if done wrong, you got to post your projects in relevant sub-reddit, for starters, you can post this at r/CoolGithubProjects
* If you have a YouTube channel then make a cool video on your software (but your software needs to have the core functionality correct) (If you have decent followers then you could get a lot of visibility). If yoiu don't have a YouTube channel then try to start one, try to do videos like Codebullet or Bisqwit or Ben Awad that relate to your projects in someway to make people try them once.
* Make famous Linux YouTubers cover your project. This will be hard and can backfire, YouTubers like DistroTube cover a lot of software reviews for linux, if you get just one video from him about your project, then I could assure you that your project will be trending **on the condition that it has good user-interface and has no bugs, also has ease to install**. Try reaching him via Reddit or E-Mail.
* Have a blog and write about your software, some people might search for something like "open source software for local file backup", if your blog has a post like solving that issue by using your software, some might benefit.

That's all the tricks I know but I think are a lot of other ways too, like Discord which I'm not familiar with.

> Whether you would consider starring the project if you find it valuable

Yeah sure.

> Any insights on how to effectively promote and grow an open-source project

You should read the answer for question 2 on this but to add more to this topic, You should not work only on your projects to grow, you should join a lot of communities and small projects and contribute to them, you will get a lot of experience and get a lot smarter working with other smart people. Find projects which you like. But I would also think that having a great YouTube channel would really improve, it should be educational and fun like Fireship, that is the key. Also use platforms like YT Shorts, TikTok and Instagram to attract a lot of people using cool uses for your software.

You can also stream like Jon Gjengset (https://www.youtube.com/@jonhoo).


I'm no expert but I think this information somehow helped you.

Best Regards,
Antony J.R
